// <auto-generated />
namespace MovieReviewsBackend.Migrations.MovieMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class FieldNeeded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FieldNeeded));
        
        string IMigrationMetadata.Id
        {
            get { return "201803311910213_FieldNeeded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
